server:
  port: 8888
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: /
#    username: guest
#    password: guest
apm:
  protocol: https://
  host: portal-apm-ibms-eks005.bm.wise-paas.com.cn
  version: APM 2.5.0
  machine:
    create-machine-path: /api-apm/topo/node
    add-profile-path: /api-apm/digital-twin/model
    property-path: /api-apm/property
ibms:
  groupId: c5785734-7944-450c-a11b-bead55b2c49f
  type: SCADA
  deviceId: SCADA@c5785734-7944-450c-a11b-bead55b2c49f@P01_AA
  groupName: linkou
  deviceName: AA
  deviceType: OPCUA
  deviceCategory: ibmsMachineProfile
